[project]
name = "labeler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=0.6.2",
    "pygithub>=2.7.0",
    "python-dotenv>=1.1.1",
]

